### PR TITLE
Add support for EDIMAX ew-7822umx (7392:6822)

### PR DESCRIPTION
**Pull request by tangruize**
Hi there!

This PR adds support for the EDIMAX ew-7822umx USB WiFi device (7392:6822). You can find the official driver [here](https://www.edimax.com/edimax/mw/cufiles/files/download/Driver_Utility/EW-7822UMX/EW-7822UMX_Linux_Driver_1.0.0.3.zip).

Changes made: incorporated modifications based on the official driver.

However, I'm unsure if the modifications may have unintended consequences for other drivers. I don't know if it can work normally if just adding the major and minor device number.

### CODE REVIEW

**Comment by morrownr** [comment]
Hi @tangruize 

I am reading your PR. Interesting. I appreciate the help.

> I'm unsure if the modifications may have unintended consequences for other drivers.

The version and date of this driver is the same as the one on the EdiMax site. What I think we need to do is discuss each of the proposed changes. I can cherry pick and add the changes one at a time if that helps us stay organized. What would help me is if I understood the reason for each change. I understand adding the vip/pid so need to discuss it.

@morrownr

**Comment by tangruize** [comment]
I've conducted testing by solely incorporating the device number. It functions as expected with no discernible impact on transfer speeds.
I think it could suffice to include just the device number line:
https://github.com/tangruize/rtl8852bu/commit/d6a3f812320e09b2d97cb4c8c4255b67f228bbef

If this approach aligns with your expectations, please check the new PR #15 .

**Comment by morrownr** [comment]
@tangruize 

Let's talk about the following:

-/* #define CONFIG_RTW_LED */
+#define CONFIG_RTW_LED
#ifdef CONFIG_RTW_LED
-	#define CONFIG_RTW_SW_LED
+	/*#define CONFIG_RTW_SW_LED*/
	#ifdef CONFIG_RTW_SW_LED
		/* #define CONFIG_RTW_LED_HANDLED_BY_CMD_THREAD */
	#endif

What was the result of the above?

**Comment by tangruize** [comment]
It seems that the code is related to the LED.
But without the modification, the LED also works as expected.

**Comment by morrownr** [comment]
> It seems that the code is related to the LED. But without the modification, the LED also works as expected.

I tested this and merged the change. LED was not working as the driver was. Now the LED is working. Thanks.

**Comment by morrownr** [comment]
@tangruize 

Now that we have 2 parts of your original PR merged, we can take a look at additional items. 

I have looked at the powertable related items and am of the opinion that it might not be a good idea given that the driver here will be used by many users of various adapters. Is there a specific issue you are trying to fix?

If you discover additional issues that need attention, please feel free to discuss them with me or submit PR's. Please submit 1 PR per issue.

@morrownr

**Pull request closed without merging**
